{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-graphql",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.springframework.graphql",
          "module": "spring-graphql",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-graphql-4.1.0.jar",
          "url": "spring-boot-graphql-4.1.0.jar",
          "size": 72115,
          "sha512": "1082299246dc9b6413e1e4c4c3c82d066ea71b7637beab96b47e08da0f55dd31ece505ee0e5c1aefaa3f041cbba9f85f2a0ade09fa791aa8cf1e286bc7224b12",
          "sha256": "06808a8b559c41be05f506e72620f8074a5a3610a6ab84aa5007a1d8449fae95",
          "sha1": "a336c66e5a5fa0a2d9d9b6002e8b4732ce1171ad",
          "md5": "b13374929b76678d89ce7476256a3255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.springframework.graphql",
          "module": "spring-graphql",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-graphql-4.1.0.jar",
          "url": "spring-boot-graphql-4.1.0.jar",
          "size": 72115,
          "sha512": "1082299246dc9b6413e1e4c4c3c82d066ea71b7637beab96b47e08da0f55dd31ece505ee0e5c1aefaa3f041cbba9f85f2a0ade09fa791aa8cf1e286bc7224b12",
          "sha256": "06808a8b559c41be05f506e72620f8074a5a3610a6ab84aa5007a1d8449fae95",
          "sha1": "a336c66e5a5fa0a2d9d9b6002e8b4732ce1171ad",
          "md5": "b13374929b76678d89ce7476256a3255"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-graphql-4.1.0-javadoc.jar",
          "url": "spring-boot-graphql-4.1.0-javadoc.jar",
          "size": 202836,
          "sha512": "b21ea4ca0bb578cb0f52fa71b38b39699fbb8383fe82f058d2767aea1aa176bfc41e1d3d2d12d981821d0f5305e604727073d087f49816f963d264b49fc91dc9",
          "sha256": "18f44555dee08841fe2981c326102bc7a3773ae86d0f130c557d947f90dec792",
          "sha1": "689ee27354124a956039cab476d6f449305cf754",
          "md5": "483d6f07e0326f80035f3a6806a09049"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-graphql-4.1.0-sources.jar",
          "url": "spring-boot-graphql-4.1.0-sources.jar",
          "size": 41279,
          "sha512": "ee8e6de8d23b0e4fce3ac3853c4268974ba5c825507d2266df8b00ee387505fa258215d30da8d4e0979a9949704e3e51b8c723154017d731c186650ec1a9000d",
          "sha256": "fe8b63d11a3416b5491019703e778470b8bc297e001c960bf616eddbd3a8090e",
          "sha1": "f57374218d0d906d448ac2e405f2cb85e833fc02",
          "md5": "2f2c89b046bc2c4dfbf8c175a82a054c"
        }
      ]
    }
  ]
}
