{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.orm",
    "module": "hibernate-core",
    "version": "7.4.1.Final",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "7.4.1.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "hibernate-core-7.4.1.Final.jar",
          "url": "hibernate-core-7.4.1.Final.jar",
          "size": 15258514,
          "sha512": "9aa692144ddd310b25829eb39046ea426d2a21f5520f5f067c2f9695ed03197c96cc5a04dc97f5443dd71ff02f772cbaea410bb7be87bacb154d43a409c13797",
          "sha256": "e4bfe7df423f3555f322eefb1ab51f28df439844610ef76c36d92a85d483004e",
          "sha1": "b405096e4aa04ff9c99a3e6e632eb2b8d252e1f1",
          "md5": "aa284ba1f033426944be07a7435f493c"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-core",
          "version": "7.4.1.Final"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-core",
          "version": "7.4.1.Final"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jboss.logging",
          "module": "jboss-logging",
          "version": {
            "requires": "3.6.1.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.models",
          "module": "hibernate-models",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.8"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.7"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "7.4.1.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1, 3[",
            "requires": "[2.17.1, 3[",
            "prefers": "2.17.1"
          },
          "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-44832: Log4j vulnerable to remote code execution and other critical security vulnerabilities"
        }
      ],
      "files": [
        {
          "name": "hibernate-core-7.4.1.Final.jar",
          "url": "hibernate-core-7.4.1.Final.jar",
          "size": 15258514,
          "sha512": "9aa692144ddd310b25829eb39046ea426d2a21f5520f5f067c2f9695ed03197c96cc5a04dc97f5443dd71ff02f772cbaea410bb7be87bacb154d43a409c13797",
          "sha256": "e4bfe7df423f3555f322eefb1ab51f28df439844610ef76c36d92a85d483004e",
          "sha1": "b405096e4aa04ff9c99a3e6e632eb2b8d252e1f1",
          "md5": "aa284ba1f033426944be07a7435f493c"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-core",
          "version": "7.4.1.Final"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-core",
          "version": "7.4.1.Final"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-core-7.4.1.Final-javadoc.jar",
          "url": "hibernate-core-7.4.1.Final-javadoc.jar",
          "size": 34589778,
          "sha512": "e9b9a634bc2302ebe6af3bd233a45d81bd9d05c6946f9ddaf6760c8b8104cd573776ef952daaa797649a46d15dab8066222249bd2209b2d0a5d01567899a706c",
          "sha256": "f4c07662aa9879296ce27da8795adf75483ab9e66beaa489e1b0c7b724f9543d",
          "sha1": "8b95d6bbe5dd1494b08e8b02b2fa04362c97a255",
          "md5": "46e91eca230b349bdc058d1455af35d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-core-7.4.1.Final-sources.jar",
          "url": "hibernate-core-7.4.1.Final-sources.jar",
          "size": 8491016,
          "sha512": "68d6ecc8b9bc991bbfd924dd6404a79e269f9cd0ffc78b3d328b343586350c196f949cc1c5a9dc85da97e4b7af8121af995978feb249a5366cebba097f98fc7f",
          "sha256": "9b545416316f49f65539654f55b408729bcaa75927d3173272cc5620da4b7b6b",
          "sha1": "0236981b5b5f66a6af26449ce81d1c4d6ea00d07",
          "md5": "822d6bab9eb124a51a80664ce99bbb3e"
        }
      ]
    }
  ]
}
